name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Load environment variables from repository settings,
    # environment should be named "production"
    # https://github.com/cadence-workflow/Cadence-Docs/settings/environments
    environment: production
    env:
      CADENCE_DOCS_URL: ${{ vars.CADENCE_DOCS_URL }}
      BASE_URL: ${{ vars.BASE_URL }}
      ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME }}

    steps:
      - name: Set environment variables
        env:
          REPO_NAME: ${{ github.repository }}
        id: split
        run: |
          if [[ -z "${PROJECT_NAME}" ]]; then
            echo "PROJECT_NAME not provided, using last part of repository name"
            echo "PROJECT_NAME=${REPO_NAME##*/}" >> $GITHUB_ENV
          fi
          if [[ -z "${BASE_URL}" ]]; then
            echo "BASE_URL not provided, using repo name for gh-pages"
            echo "BASE_URL=/${REPO_NAME##*/}/" >> $GITHUB_ENV
          fi
          if [[ -z "${ORGANIZATION_NAME}" ]]; then
            echo "ORGANIZATION_NAME not provided, using the first part of the repository name"
            echo "ORGANIZATION_NAME=${REPO_NAME/\/*/}" >> $GITHUB_ENV
          fi

      # same as build.yml
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # configure custom domain for github pages
      # files placed under static folder will be copied to the root of the build folder
      - name: Configure domain
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "static/CNAME"
          FILE_DATA: ${{ secrets.CUSTOM_DOMAIN }}

      - name: Use Node.js lts/jod (v22)
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: "npm"

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch

      - name: Re-index Algolia search 🔍
        env:
          APPLICATION_ID: N9YD9IU5NA
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        run: |
          if [ -z "$API_KEY" ]; then
            echo "ALGOLIA_ADMIN_API_KEY secret not set, skipping re-indexing"
            exit 0
          fi
          # Pinned to https://hub.docker.com/v2/repositories/algolia/docsearch-scraper/tags/latest
          # on 2026-04-13, please update this to the latest version occasionally.
          docker run --rm \
            -e APPLICATION_ID \
            -e API_KEY \
            -e "CONFIG=$(cat docsearch-config.json | jq -r tostring)" \
            algolia/docsearch-scraper@sha256:7bc1cd5aa4783bf24be9ddd6ef22a629b6b43e217b3fa220b6a0acbdeb83b8f8
