name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Load environment variables from repository settings,
    # environment should be named "production"
    # https://github.com/cadence-workflow/Cadence-Docs/settings/environments
    environment: production
    env:
      CADENCE_DOCS_URL: ${{ vars.CADENCE_DOCS_URL || 'https://cadenceworkflow.io' }}
      BASE_URL: ${{ vars.BASE_URL || '/Cadence-Docs/' }}
      ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME || 'cadence-workflow' }}

    steps:
    - name: Split branch name
        env:
          PROJECT_NAME: ${{ github.repository }}
        id: split
        run: echo "fragment=${PROJECT_NAME##*/}" >> $GITHUB_OUTPUT
    - name: Test variable
        run: |
          echo ${{ steps.split.outputs.fragment }}
          echo $PROJECT_NAME

      # same as build.yml
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # configure custom domain for github pages
      - name: Configure domain
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "static/CNAME"
          FILE_DATA: ${{ secrets.CUSTOM_DOMAIN || 'cadenceworkflow.io' }}

      - name: Use Node.js lts/hydrogen (v18)
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
